# Generated by Django 4.2.6 on 2023-10-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_employeedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('eemployee', models.CharField(blank=True, max_length=50, null=True)),
                ('pdiscription', models.CharField(blank=True, max_length=50, null=True)),
                ('paddress', models.CharField(blank=True, max_length=50, null=True)),
                ('proom', models.CharField(blank=True, max_length=50, null=True)),
                ('ptoilet', models.CharField(blank=True, max_length=50, null=True)),
                ('squarfeet', models.CharField(blank=True, max_length=50, null=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='proprofile')),
                ('pimage1', models.ImageField(blank=True, null=True, upload_to='proprofile')),
                ('pimage2', models.ImageField(blank=True, null=True, upload_to='proprofile')),
            ],
        ),
    ]
