# Generated by Django 4.2.6 on 2023-10-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_propertytype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='propertytype',
            new_name='propertytypedb',
        ),
    ]
