# Generated by Django 4.2.6 on 2023-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_selltypedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydb',
            name='parea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydb',
            name='ptype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydb',
            name='stype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
