# Generated by Django 4.2.6 on 2023-11-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_propertydb_parea_propertydb_ptype_propertydb_stype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydb',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
