# Generated by Django 4.2.6 on 2023-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_propertydb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydb',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
