# Generated by Django 4.2.6 on 2023-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_alter_propertydb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
