# Generated by Django 4.2.6 on 2023-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdb',
            name='cmessage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='csubject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
