# Generated by Django 4.2.6 on 2023-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_useremployeedb_usersignupdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignupdb',
            name='uimage',
            field=models.ImageField(default='profile.png', upload_to='user_profile'),
        ),
    ]
