# Generated by Django 4.2.6 on 2023-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0005_alter_usersignupdb_uimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignupdb',
            name='uimage',
            field=models.ImageField(default='profile.png', upload_to='user_profile'),
        ),
    ]
