# Generated by Django 4.2.6 on 2023-11-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_alter_usersignupdb_uimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremployeedb',
            old_name='confirmpass',
            new_name='econfirmpass',
        ),
        migrations.RenameField(
            model_name='useremployeedb',
            old_name='upassword',
            new_name='epassword',
        ),
        migrations.RenameField(
            model_name='useremployeedb',
            old_name='uusername',
            new_name='eusername',
        ),
    ]
