# Generated by Django 4.2.6 on 2023-11-22 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FrontEnd', '0007_rename_confirmpass_useremployeedb_econfirmpass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unumber', models.CharField(blank=True, max_length=50, null=True)),
                ('uemail', models.CharField(blank=True, max_length=50, null=True)),
                ('uusername', models.CharField(blank=True, max_length=50, null=True)),
                ('upassword', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmpass', models.CharField(blank=True, max_length=500, null=True)),
                ('uimage', models.ImageField(default='profile.png', upload_to='user_profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
