# Generated by Django 4.2.6 on 2023-11-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
