# Generated by Django 4.2.6 on 2023-11-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
